cmake .. \
 -DCMAKE_CXX_COMPILER=g++\
 -DCMAKE_INSTALL_PREFIX=build \
 -DCMAKE_BUILD_TYPE=Debug \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ARCH_TURING75=ON \
 -DKokkos_ENABLE_EXAMPLES=ON \
 -DKokkos_ENABLE_OPENMP=ON